#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

nm-applet &
fbsetbg ~/.fluxbox/styles/base16-default-dark/base16.jpg &
dropbox start &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/vrockai/.fluxbox/log"
